[package]
name = "findora-terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1", features = ["v5"] }

mfrc522 = { version = "0.8", optional = true }
linux-embedded-hal = { version = "0.4", features = ["spi"], optional = true }

[features]
rc522 = ["mfrc522", "linux-embedded-hal"]